# See https://docs.redoc.ly/cli/configuration/ for more information.
apiDefinitions:
  main: "openapi/openapi.yaml"
  rock: openapi/rock.yaml
  paper: openapi/paper.yaml
  scissors: openapi/scissors.yaml
lint:
  rules:
referenceDocs:
  htmlTemplate: ./docs/index.html
  theme:
    colors:
      primary:
        main: "#32329f"